version: '3'
services:
  pancaketrade:
    image: vbersier/pancaketrade:latest
    restart: unless-stopped
    container_name: pancaketrade
    tty: true
    env_file: .env # add a WALLET_PK environment variable with your private key in that file
    volumes:
      - type: bind
        source: ./user_data
        target: /app/user_data
