---
bsc_rpc: https://bsc-dataseed.binance.org # you can use any BSC RPC url you want
min_pool_size_bnb: 25 # PancakeSwap LPs that have less than 25 BNB will not be considered
monitor_interval: 5 # the script will check the token prices with this interval in seconds
update_messages: true # status messages will update periodically to show current values
secrets:
  telegram_token: '' # enter your Telegram Bot token
  admin_chat_id: 123456 # enter your chat ID/user ID to prevent other users to use the bot
  # rpc_auth_user: '' # if your RPC requires basic HTTP auth, you can indicate credentials here and uncomment this line
  # rpc_auth_password: '' # if your RPC requires basic HTTP auth, you can indicate credentials here and uncomment this line
